#!/usr/bin/python

import sys, time

def main():
	try:
		waitdown()
	except (KeyboardInterrupt, SystemExit):
		sys.stdout.write('\nwaiter interrupted by keyboard.\n')
		sys.stdout.flush()
		sys.exit()
	sys.stdout.write('\n')
	sys.stdout.flush()

def waitdown():
	count = int(sys.argv[1]) -1
	while(count >= 0):
		s = "Resuming in " + str(count) + "s"
		sys.stdout.write('\r' + s)
		sys.stdout.flush()
	 	count = count - 1
		time.sleep(1)

if __name__ == "__main__":
	main()
