#!/usr/bin/python

import sys,time

def main():
	try:
		waitdown()
	except (KeyboardInterrupt, SystemExit):
		sys.stdout.write('\nwaiter interrupted by keyboard.\n')
		sys.stdout.flush()
		sys.exit()
	sys.stdout.write('\n')
	sys.stdout.flush()

def waitdown():
	count = int(sys.argv[1]) -1
	b = ''
	s = ''
	while(count >= 0):
		s = "Resuming in " + str(count).zfill(5) + "s"
		sys.stdout.write('\r%s' % s)
		sys.stdout.flush()
		count = count - 1
		time.sleep(1)

if __name__ == "__main__":
	main()
